site:
  title: Sorting Components and Versions
  url: http://example.com
  start_page: 1@component-a:ROOT:index.adoc

content:
  sources:
  - url: .
    start_paths:
    - cav1
    - cav2
    - cav3
    - cbv1
    - cbv2
    - cbv3
    - ccv1
    - ccv2
    - ccv3
    - hidden

asciidoc:
  attributes:
# hide explicit component, show all unmentioned components:
    page-component-sort-order: component-b, !hidden, component-c , *
# hide all unmentioned components:
#    page-component-sort-order: component-b, component-c , !*
# don't warn on not-existing component:
#    page-component-sort-order: not-a-component?, component-b, !hidden, component-c , *

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_uis/component_version

output:
  clean: true
