site:
  title: Sorting Components and Versions
  url: http://example.com
  start_page: 1@component-a:ROOT:index.adoc

content:
  sources:
  - url: .
    start_paths:
    - cav1
    - cav2
    - cav3
    - cbv1
    - cbv2
    - cbv3
    - ccv1
    - ccv2
    - ccv3
    - hidden

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_uis/component_silly

output:
  dir: build-silly
  clean: true
